mysite/hello/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
      url(r'^$', views.hello_world, name='hello_world'),
      url(r'^template/$', views.hello_template, name='hello_template'),
      url(r'^if/$', views.hello_if, name='hello_if'),
      url(r'^for/$', views.hello_for, name='hello_for'),
      url(r'^get/$', views.hello_get_query, name='hello_get_query'),
      url(r'^forms/$', views.hello_forms, name='hello_forms'),
      url(r'^form_samples/$', views.hello_forms2, name='hello_forms2'), 
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]
from django.conf.urls import include, url


urlpatterns = [
      url(r'^hello/', include('hello.urls', namespace='hello')),
      url(r'^wsp_time/', include('wsp_time.urls', namespace='wsp_time')),
]

mysite/wsp_time/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
     url(r'^$', views.index, name='index'),
     url(r'^add/$', views.add, name='add'),
     url(r'^delete/$', views.delete, name='delete'),
     url(r'^edit/(?P<editing_id>\d+)/$', views.edit, name='edit'),
]

mysite/hello/forms.py
# coding: utf-8
from django import forms


class HelloForm(forms.Form):
      your_name = forms.CharField(
          label='名前',
          max_length=20,
          required=True,
          widget=forms.TextInput()
      )

EMPTY_CHOICES = (
     ('', '-'*10),
)

GENDER_CHOICES = (
       ('man', '男'),
       ('woman', '女')
)

FOOD_CHOICES = (
     ('apple', 'りんご'),
     ('beef', '牛肉'),
     ('bread', 'パン'),

)


class SampleForm(forms.Form):
    age = forms.IntegerField(
        label='年齢',
        min_value=0,
        max_value=200,
        required=True,
    )

    birthday = forms.DateField(
           label='生年月日',
           required=True,
           input_formats=[
               '%Y-%m-%d',  # 2010-01-01
               '%Y/%m/%d',  # 2010/01/01
           ]
    )

    send_message = forms.BooleanField(
          label='送信する',
          required=False,
    )

    gender_r = forms.ChoiceField(
         label='性別',
        widget=forms.RadioSelect,
         choices=GENDER_CHOICES,
         required=True,
    )

    gender_s = forms.ChoiceField(
         label='性別',
         widget=forms.Select,
         choices=EMPTY_CHOICES + GENDER_CHOICES,
         required=False,
    )

    food_s = forms.ChoiceField(
        label='食べ物',
           widget=forms.SelectMultiple,
           choices=FOOD_CHOICES,
           required=True,
    )

    food_c = forms.ChoiceField(
           label='食べ物',
           widget=forms.CheckboxSelectMultiple,
           choices=FOOD_CHOICES,
          required=True,
    )

mysite/wsp_time/forms.py
# coding: utf-8
from django import forms


class TimeForm(forms.Form):

    EMPTY_CHOICES = (
         ('', '-'*10),
    )

    NAME_CHOICES = (
         ('oomori', '大森'),
         ('shimizu', '清水'),
         ('tomizawa', '富澤'),

    )

    PLACE_CHOICES = (
         ('sagamigawa', '相模川'),
         ('misakiguchi', '三崎口')
    )
    distance = forms.IntegerField(
        label='距離',
        min_value=1,
        max_value=20,
        required=True,
    )

    day = forms.DateField(
           label='日付',
           required=True,
           input_formats=[
               '%Y-%m-%d',  # 2010-01-01
               '%Y/%m/%d',  # 2010/01/01
           ]
    )

    time = forms.DateField(
           label='タイム',
           required=True,
           input_formats=[
               '%i-%s',  # 20-01
               '%i/%s',  # 20/01
           ]
    )

    send_message = forms.BooleanField(
          label='送信する',
          required=False,
    )

    name_s = forms.ChoiceField(
         label='名前',
         widget=forms.Select,
         choices=EMPTY_CHOICES + NAME_CHOICES,
         required=False,
    )

    place_s = forms.ChoiceField(
         label='場所',
         widget=forms.Select,
         choices=EMPTY_CHOICES + PLACE_CHOICES,
         required=False,
    )

mysite/hello/views.py
#! /usr/bin/env python
# -*- coding: UTF-8 -*-
from django.shortcuts import render

# Create your views here.
from datetime import datetime
from django.http.response import HttpResponse
from django.shortcuts import render
from . import forms

def hello_world(request):
      return HttpResponse('Hello World!')

def hello_template(request):
      return render(request, 'index.html')

def hello_template(request):
    d = {
          'hour': datetime.now().hour,
          'message': 'Sample message',
    }
    return render(request, 'index.html', d)


def hello_if(request):
    d = {
        'is_visible': False,
        'empty_str': '',
    }
    return render(request, 'if.html', d)

def hello_for(request):
    d = {
        'objects': range(10),
    }
    return render(request, 'for.html', d)

def hello_get_query(request):
    d = {
        'your_name': request.GET.get('your_name')
    }
    return render(request, 'get_query.html', d)

def hello_forms(request):
    form = forms.HelloForm(request.GET or None)
    if form.is_valid():
        message = 'データ検証に成功しました'
    else:
        message = 'データ検証に失敗しました'
    d = {
        'form': form,
        'message': message,
    }
    return render(request, 'forms.html', d)

def hello_forms2(request):
    d = {
        'form': forms.SampleForm(),
    }
    return render(request, 'form_samples.html', d)

mysite/templates/base.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

mysite/templates/for.html
{% extends "base.html" %}
{% block body %}
{% for idx in objects %}
    {{ idx }}<br>
{% endfor %}
{% endblock %}

mysite/templates/form_samples.html
{% extends "base.html" %}

{% block body %}
  <form method="get" action="">
     {{ form.distance.label }}：
     {{ form.distance }}
     <hr>

     {{ form.name_r.label }}：
     {% for name in form.name_r %}
        {{ name }}
     {% endfor %}
     <hr>

     {{ form.name_s.label }}：
     {{ form.name_s }}
     <hr>

     {{ form.send_message.label }}：
     {{ form.send_message }}
     <hr>

     {{ form.day.label }}：
     {{ form.day }}
     <hr>

     {{ form.place_r.label }}：
     {% for place in form.place_r %}
        {{ place }}
     {% endfor %}
     <hr>

     {{ form.place_s.label }}：
     {{ form.place_s }}
     <hr>

  </form>
{% endblock %}

mysite/templates/forms.html
{% extends "base.html" %}

{% block body %}
  {{ message }}
  <hr>
  <form method="get" action="">
      {{ form.errors.your_name }}
      <label>{{ form.your_name.label }} {{ form.your_name }}</label><br>

      {{ form.errors.gender}}
      <label>{{ form.gender.label }} {{ form.gender }}</label><br>

      {{ form.errors.memo }}
      <label style="vertical-align: top;">{{ form.memo.label }} {{ form.memo }}</label><br>

      <input type="submit" value="送信">
  </form>
{% endblock %}

mysite/templates/get_query.html
{% extends "base.html" %}

{% block body %}
    <form action="" method="get">
        <label>名前:<input type="text" size="20" name="your_name"></label>
        <input type="submit" value="送信">
    </form>
    {% if your_name %}
        {{ your_name }}さん、こんにちは。
    {% endif %}
{% endblock %}

mysite/templates/if.html
{% extends "base.html" %}
{% block body %}
{% if is_visible %}
is_visibleがTrueなので表示します。<br>
{% else %}
is_visibleがFalseなので表示します。<br>
{% endif %}

{% if empty_str|length > 0 %}
empty_strの文字数は{{ empty_str|length }}です。
{% else %}
empty_strが空です。<br>
{% endif %}
{% endblock %}

mysite/templates/index.html
{% extends "base.html" %}

{% block body %}
 <div>
   {{ hour }}時です。<br>
   {{ message }}
 </div>
 <div>
   <a href="{% url 'hello:hello_world' %}">hello_world</a><br>
   <a href="{% url 'hello:hello_template' %}">template</a><br>
   <a href="{% url 'hello:hello_if' %}">if</a><br>
   <a href="{% url 'hello:hello_for' %}">for</a><br>
 </div>
{% endblock %}

mysite/templates/index_wsp.html
{% extends "base.html" %}

{% block body %}
 <div>
   練習記録<br>
 </div>
 <div>
   <a href="{% url 'hello:hello_world' %}">hello_world</a><br>
   <a href="{% url 'hello:hello_template' %}">template</a><br>
   <a href="{% url 'hello:hello_if' %}">if</a><br>
   <a href="{% url 'hello:hello_for' %}">for</a><br>
 </div>
{% endblock %}

mysite/templates/wasepa.html
<ul id="normal" class="dropmenu">
  <li><a href="#">menu</a>
    <ul>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      </ul>
    </li>
  <li><a href="#">menu</a>
    <ul>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
    </ul>
  </li>
    <li><a href="#">menu</a>
     <ul>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
     </ul>
    </li>
  <li><a href="#">menu</a>
    <ul>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
    </ul>
  </li>
  <li><a href="#">menu</a>
    <ul>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
      <li><a href="#">submenu</a></li>
    </ul>
  </li>
</ul>

mysite/templates/wsp.html
<html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" /> </head>
<body>
   <form action="/wsp_home"
         method="GET">
    <select name="day">
     <option value="getu">月</option>
     <option value="ka">火</option>
     <option value="sui">水</option>
     <option value="moku">木</option>
     <option value="kinn">金</option>
     <option value="do">土</option>
     <option value="niti">日</option>
    </select>

　　<input type="radio" name="place" value="sagamigawa">相模川 <input type="radio" name="place" value="misakiguti">三崎口

　　<input type="checkbox" name="time" value="7:00">7:00
　　<input type="checkbox" name="time" value="15:00">15:00

    <textarea name="body_text" cols="40" rows="20" >文章を入力してください</textarea>

    <input type="submit" value="送信">
  </form>
 </body>
</html>

mysite/templates/wsp_boy.html
<html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" /> </head>
<body>
   <form action="/wsp_home"
         method="POST">
    <select name="day">
     <option value="getu">月</option>
     <option value="ka">火</option>
     <option value="sui">水</option>
     <option value="moku">木</option>
     <option value="kinn">金</option>
     <option value="do">土</option>
     <option value="niti">日</option>
    </select>


    <input type="submit" value="送信">
  </form>
 </body>
</html>

mysite/templates/wsp_home.html
<html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" /> </head>
<body>
   <form action="/cgi-bin/wsp.py"
         method="POST">
     <table>
        <caption>今週の日程</caption>
        <tr>
          <th colspan="2">月</th>
          <th colspan="2">火</th>
          <th colspan="2">水</th>
          <th colspan="2">木</th>
          <th colspan="2">金</th>
          <th colspan="2">土</th>
          <th colspan="2">日</th>
        </tr>
        <tr>
          <td colspan="2">{{get('area_1','no')}}</td>
          <td colspan="2">{{get('area_2','no')}}</td>
          <td colspan="2">{{get('area_3','no')}}</td>
          <td colspan="2">{{get('area_4','no')}}</td>
          <td colspan="2">{{get('area_5','no')}}</td>
          <td colspan="2">{{get('area_6','no')}}</td>
          <td colspan="2">{{get('area_7','no')}}</td>
        </tr>
        <tr>
          <td>{{get('time_1_1','no')}}</td>
          <td>{{get('time_1_2','no')}}</td>
          <td>{{get('time_2_1','no')}}</td>
          <td>{{get('time_2_2','no')}}</td>
          <td>{{get('time_3_1','no')}}</td>
          <td>{{get('time_3_2','no')}}</td>
          <td>{{get('time_4_1','no')}}</td>
          <td>{{get('time_4_2','no')}}</td>
          <td>{{get('time_5_1','no')}}</td>
          <td>{{get('time_5_2','no')}}</td>
          <td>{{get('time_6_1','no')}}</td>
          <td>{{get('time_6_2','no')}}</td>
          <td>{{get('time_7_1','no')}}</td>
          <td>{{get('time_7_2','no')}}</td>
        </tr>
        <tr>
          <td>{{get('p_1_1','no')}}</td>
          <td>{{get('p_1_2','no')}}</td>
          <td>{{get('p_2_1','no')}}</td>
          <td>{{get('p_2_2','no')}}</td>
          <td>{{get('p_3_1','no')}}</td>
          <td>{{get('p_3_2','no')}}</td>
          <td>{{get('p_4_1','no')}}</td>
          <td>{{get('p_4_2','no')}}</td>
          <td>{{get('p_5_1','no')}}</td>
          <td>{{get('p_5_2','no')}}</td>
          <td>{{get('p_6_1','no')}}</td>
          <td>{{get('p_6_2','no')}}</td>
          <td>{{get('p_7_1','no')}}</td>
          <td>{{get('p_7_2','no')}}</td>
        </tr>
     </table>
   <a href="/">予定設定</a><br>
   <a href="/views/wsp_boy.html">出欠確認</a><br>

  </form>
 </body>
</html>

mysite/templates/wsp_time/edit.html
{% extends "base.html" %}

{% block body %}
  <a href="{% url 'wsp_time:index' %}">自己ベストタイム表へ</a>
  <form method="get" action="">
     {{ form.day.label }}：
     {{ form.day }}
     <hr>

     {{ form.name_s.label }}：
     {{ form.name_s }}
     <hr>

     {{ form.place_s.label }}：
     {{ form.place_s }}
     <hr>

     {{ form.distance.label }}：
     {{ form.distance }}
     <hr>

     {{ form.time.label }}：
     {{ form.time }}
     <hr>

     {{ form.errors.message }}
     <label>{{ form.message.label }}{{ form.message }}</label><br/>
     {% csrf_token %}
     <input type="submit" value="登録">

  </form>
{% endblock %}

mysite/templates/wsp_time/index.html
{% extends "base.html" %}

{% block body %}
<a href="{% url 'wsp_time:add' %}">登録画面へ</a>
  <form method="post" action="">
    <table border="1">
     <thead>
      <tr>
        <th>message</th>
        <th>created_at</th>
        <th>updated_at</th>
        <th>　</th>
      </tr>
     </thead>
     <tbody>
      {% for message in messages %}
        <tr>
          <td>{{ message.message }}</td>
          <td>{{ message.created_at }}</td>
          <td>{{ message.updated_at }}</td>
          <td><a href="{% url 'wsp_time:edit' message.id %}">更新画面へ</a></td>
        </tr>
      {% endfor %}
     </tbody>
    </table>
  </form>
{% endblock %}